---
title: "Exploratory Data Analysis TEFF"
author: "ICRISAT"
date: "2024-02-16"
output: html_document
---
```{r}
# Load the required packages
library(tidyverse)
library(GGally)
library(skimr)
library(lme4)
library(tmap)
library(gtsummary)
library(terra)
library(plotly)
library(FactoMineR)
library(ggmap)
library(knitr)
library(ggspatial)
library(leaflet)
library(leaflet.extras)
library(ggplot2)
library(readr)
library(sf)
library(shiny)
library(plotly)
library(dplyr)
library(plyr)
library(sp)
library(lubridate)
library(inspectdf)
library(sf)
```


```{r}
getwd()
setwd("C:/Users/HDesalegn/eia-ethiopia/EDA-teff-R")
```

```{r}
# Ingest data

df <- read.csv("teff_dst_team_shared_v1.csv")
```

```{r}
colnames(df)
```


```{r}
# Overview of the data
str(df)
```


```{r}
# sneak peak at sample entry

sample_n(df, 10)
```


```{r}
# Summary statistics

summary(df)
```


```{r}
# Data manipulation

# Convert numeric columns to numeric type
# df <- df %>% mutate(across(c(n_kgpha, p_kgpha, k_kgpha, grain_yield_kgpha), as.numeric))

# Convert factors
# df <- df %>% mutate(across(where(is.character), as.factor))

# Check for missing values
missing_values <- sum(is.na(df))

# Calculate the percentage of missing values
percentage_missing <- (missing_values / length(df)) * 100

cat("Percentage missing:", percentage_missing, "%\n")
```
```{r}
df |>
  summarise_all(~sum(is.na(.)))
```
```{r}
length(unique(df$treatment))
unique(df$treatment)
```
```{r}
eth <- geodata::gadm(path = ".", "eth", level = 0) |> st_as_sf()
eth_out <- geodata::gadm(path = ".", "eth", level = 0) |> st_as_sf()
class(eth_out)
```
```{r}
# Create location by concatenating level 2 and level3

eth_dist <- geodata::gadm(path = ".", "eth", level = 3) |> st_as_sf()
teff_pts <- terra::vect(df, geom = c('long', 'lat'), crs = "epsg:4326") |> st_as_sf()
dim(teff_pts)

teff_joined <- st_join(teff_pts, eth_dist) 
teff_joined <- st_coordinates(teff_joined) |> cbind(as.data.frame(teff_joined))  |> dplyr::select(unique_id, X, Y, year, source, treatment, n_kgpha, p_kgpha, k_kgpha, grain_yield_kgpha, NAME_1, NAME_2, NAME_3)

head(teff_joined, 3)
```

```{r}
# create trialID and treatmentID

df_filtered <- teff_joined |> dplyr::mutate(NAME_1 = replace(NAME_1, NAME_1 == "Southern Nations, Nationalities", "SNNP"))|> dplyr::mutate(trial_id = paste(X, Y, year, source, sep = ",")) |> dplyr::mutate(n_rate2 = round_any(n_kgpha, 5), p_rate2 = round_any(p_kgpha, 2), k_rate2 = round_any(k_kgpha, 10)) |> dplyr::mutate(treatment_id = 
paste(n_rate2, p_rate2, k_rate2, sep = "_")) |> dplyr::mutate(location = 
paste(NAME_2, NAME_3, sep = "_"))
```

```{r}
filtered_sg_2000_data <- df_filtered %>% filter(source == "SG 2000")
filtered_sg_2000_data
```
```{r}

yield_by_location <- filtered_sg_2000_data %>%
  group_by(unique_id,X,Y,year,location) %>%
  dplyr::summarise(Average_Yield = grain_yield_kgpha) %>%
  arrange(desc(Average_Yield))

# View the summary table
print(yield_by_location)

```
```{r}
filtered_ISFM2018_data <- df_filtered %>% filter(source == "ISFM-2018")
filtered_ISFM2018_data
```

```{r}
write.csv(filtered_ISFM2018_data, "ISFM-2018.csv")
```

```{r}


# Splitting the dataset into old and new based on the year
old_data <- filter(df_filtered, year >= 1990 & year <= 2000)
new_data <- filter(df_filtered, year > 2000 & year <= 2021)

# Aggregating the yields by year and source for the old dataset
old_yield_by_year_source <- old_data %>%
  group_by(year, source) %>%
  summarise(average_yield = mean(grain_yield_kgpha, na.rm = TRUE))

# Aggregating the yields by year and source for the new dataset
new_yield_by_year_source <- new_data %>%
  group_by(year, source) %>%
  summarise(average_yield = mean(grain_yield_kgpha, na.rm = TRUE))

# Viewing the aggregated data for old and new periods
print(old_yield_by_year_source)
print(new_yield_by_year_source)

```

```{r}
# Filter observations by source and year with less than 10 observations

filtered_data <- df_filtered %>%
  group_by(source, year) %>%
  dplyr::summarise(observation_count = n(), .groups = 'drop') %>%
  filter(observation_count < 10)

print(filtered_data)
```


```{r}
# Identify outliers - points not within the Ethiopia boundary

pts_source <- dplyr::count(as_tibble(df_filtered), source)
print(pts_source[order(pts_source$n, decreasing = TRUE), ])
```

```{r}
teff_coord <- terra::vect(df_filtered, geom = c('X', 'Y'), crs = ("epsg:4326"))
```

```{r}
teff_coord_sf <- st_as_sf(teff_coord)

outliers <- teff_coord_sf[!st_within(teff_coord_sf, eth_out, sparse = FALSE), ]

leaflet() %>%
  addTiles() %>%
  addPolygons(data = eth_out, fillColor = NA, color = "blue", weight = 2) %>%
  addCircleMarkers(data = outliers, color = "red", radius = 2, fillColor = "red", fillOpacity = 1.0, popup = "Outlier Point") %>%
  setView(lng = 39.49, lat = 9.14, zoom = 6) # Center the map over Ethiopia
```

```{r}
# flag points that lie outside of Ethiopia boundary

inside_ethiopia <- st_within(teff_coord_sf, eth_out, sparse = FALSE)
flag1 <- teff_coord_sf[!inside_ethiopia, ]
flag1
```
```{r}
write.csv(flag1, "points_outside_Eth.csv")
```

```{r}
# Count the number of observations per year
observations_per_year <- df_filtered %>%
  group_by(year) %>%
  dplyr::summarise(count = n())

# Display observations per year
print(observations_per_year)

# Identify years with very few trials (1 or 2 observations)
years_with_few_trials <- observations_per_year %>%
  filter(count <= 2) %>%
  pull(year)

# Separate data for years with few trials from the main dataset
data_with_few_trials <- df_filtered %>%
  filter(year %in% years_with_few_trials)

data_remaining <- df_filtered %>%
  filter(!(year %in% years_with_few_trials))

# Calculate the average grain yield for years with few observations
average_yield_few_trials <- mean(data_with_few_trials$grain_yield_kgpha)

# Calculate the average grain yield for the remaining years
average_yield_remaining <- mean(data_remaining$grain_yield_kgpha)

# Print the average yields
print(paste("Average yield for years with few trials:", average_yield_few_trials))
print(paste("Average yield for remaining years:", average_yield_remaining))

```

```{r}
# add comment column to flaged data points

flag1$comment <- "geolocation error"
flag1$description <- "Outside of the boundary of Ethiopia"
flag1
```

```{r}
df_filtered <- df_filtered |> dplyr::filter(!(unique_id %in% flag1$unique_id))
dim(df_filtered)
```

```{r}
shapefile_dir <- "teff"

trial_locations <- df_filtered

# Convert the data frame to an sf object using the coordinates
trial_locations_sf <- st_as_sf(trial_locations, coords = c("X", "Y"), crs = 4326)

# Read the shapefile
teff_growing_areas <- st_read(shapefile_dir)

# Repair invalid geometries in the teff_growing_areas shapefile
teff_growing_areas <- st_make_valid(teff_growing_areas)

# Transform the CRS of trial_locations_sf to match teff_growing_areas, if they don't match
if (st_crs(trial_locations_sf) != st_crs(teff_growing_areas)) {
  trial_locations_sf <- st_transform(trial_locations_sf, st_crs(teff_growing_areas))
}

# Perform the spatial join to find trials located within teff growing areas
trials_within_teff <- st_join(trial_locations_sf, teff_growing_areas, join = st_within)

# Identify trials located outside teff growing areas
trials_outside_teff <- trials_within_teff[is.na(trials_within_teff$COUNTRY),]

# Select relevant columns to display
result <- trials_outside_teff %>% 
  select(unique_id,location , year, source, treatment, grain_yield_kgpha, location)

print(result)
```

```{r}
# Calculate the number of observations for each source
observation_counts <- df_filtered %>% 
  group_by(source) %>% 
  dplyr::summarise(Count = n())

# Plot the bar chart
ggplot(observation_counts, aes(x = source, y = Count)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  theme_minimal() +
  labs(x = "Source", y = "Number of Observations", title = "Observations by Source for trials outside of the crop mask(TEFF)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
write.csv(trials_outside_teff, "trials_outsideET.csv")
```


```{r, message=FALSE, fig.width = 5, warning=F}
# # Identifying trials outside of the crop mask

ethiopia_map <- st_read("teff")
ethiopia_map <- st_make_valid(ethiopia_map)

# Plot
ggplot() +
  geom_sf(data = ethiopia_map, fill = "white", color = "black") + # Ethiopia's map as the base
  geom_sf(data = teff_growing_areas, fill = "lightgreen", color = "darkgreen", alpha = 0.5) + # Teff growing areas
  geom_sf(data = trials_within_teff, color = "blue", size = 2, alpha = 0.6) + # Trials within teff areas
  geom_sf(data = trials_outside_teff, color = "red", size = 2, alpha = 0.6) + # Trials outside teff areas
  theme_minimal() +
  labs(title = "Teff Trial Locations in Ethiopia",
       subtitle = "Blue: Within Teff Areas, Red: Outside Teff Areas")
```

```{r}
dim(trials_outside_teff)
```

```{r}
# boxplot of data distribution

df_filtered |> ggplot(aes(x= source, y = grain_yield_kgpha, fill= source)) + 
  geom_boxplot()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), legend.position = 'none')
```

```{r}
yield15000 <- df_filtered %>%
  filter(grain_yield_kgpha > 15000) %>%
  mutate(comment = "yield outliers", 
         description = "grain yield greater than 15K kg/ha")

print(yield15000)
```

```{r}
few_data <- df_filtered %>%
  filter(grain_yield_kgpha <= 300)
dim(few_data)
```

```{r}
# Create a leaflet map
map <- leaflet(yield15000) %>%
  addTiles() %>%
  addMarkers(
    lng = ~X, lat = ~Y,
    popup = ~paste("Source:", source, "<br>",
                   "Year:", year, "<br>",
                   "Treatment:", treatment, "<br>",
                   "Treatment ID:", treatment_id, "<br>",
                   "GrainYield:", grain_yield_kgpha, "<br>",
                   "Location:", location),
    options = popupOptions(closeButton = TRUE)
  )

print(map)

```

```{r}
# Drop observations with yield values > 10ton/ha

df_filtered <- df_filtered |> dplyr::filter(grain_yield_kgpha <= 5000)
```

```{r}
# Histogram of grain yields

ggplot(df_filtered, aes(x = grain_yield_kgpha)) +
  geom_histogram(bins = 30, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Grain Yields", x = "Grain Yield (kg/ha)", y = "Frequency") +
  theme_minimal()
```
```{r}
# Boxplots for N, P, K treatments against yield
# For N treatment
ggplot(df_filtered, aes(x = factor(n_rate2), y = grain_yield_kgpha)) +
  geom_boxplot() +
  labs(title = "Grain Yield vs N Treatment", x = "N (kg/ha)", y = "Grain Yield (kg/ha)") +
  theme_minimal()
```

```{r}
# For P treatment
ggplot(df_filtered, aes(x = factor(p_rate2), y = grain_yield_kgpha)) +
  geom_boxplot() +
  labs(title = "Grain Yield vs P Treatment", x = "P (kg/ha)", y = "Grain Yield (kg/ha)") +
  theme_minimal()
```

```{r}
# For K treatment
ggplot(df_filtered, aes(x = factor(k_rate2), y = grain_yield_kgpha)) +
  geom_boxplot() +
  labs(title = "Grain Yield vs K Treatment", x = "K (kg/ha)", y = "Grain Yield (kg/ha)") +
  theme_minimal()
```
```{r}
df_filtered |> ggplot(aes(NAME_2))+
  geom_bar(fill = "lightblue")+
  xlab("Zone")+
  ylab("observation")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12))
```

```{r}
df_filtered |> ggplot(aes(NAME_3))+
  geom_bar(fill = "lightblue")+
  xlab("District")+
  ylab("observation")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 12))
```

```{r}
# Create bar chart for each year / 
df_filtered$year <- as.factor(df_filtered$year)
df_filtered %>%
  ggplot(aes(year)) +
  geom_bar(fill = "lightblue") +
  xlab("Year") +
  ylab("Observation") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12))
```

```{r}
# Count unique trial IDs by year

trial_counts_by_year <- df_filtered %>%
  group_by(year) %>%
  dplyr::summarise(unique_trial_ids = n_distinct(trial_id))

# Bar plot of unique trial IDs by year
ggplot(trial_counts_by_year, aes(x = year, y = unique_trial_ids)) +
  geom_bar(stat = "identity", fill = "cornflowerblue") +
  labs(title = "Unique Trial IDs by Year", x = "Year", y = "Number of Unique Trial IDs") +
  theme_minimal()

```

```{r}
# Data Distribution by source

df_filtered %>%
  group_by(source) %>%
  dplyr::summarise(count = n()) %>%
  ggplot(aes(x = source, y = count, fill = source)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Data Distribution by Source", x = "Source", y = "Count")
```

```{r}
# Data distribution by location

df_filtered %>%
  group_by(location) %>%
  dplyr::summarise(count = n()) %>%
  top_n(10, count) %>% # Adjust or remove top_n as needed
  ggplot(aes(x = reorder(location, -count), y = count, fill = location)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Data Distribution by Location (Top 10)", x = "Location", y = "Count")

```

```{r}
# Observation count by source

observations_by_source_treatment <- df_filtered %>%
  group_by(source) %>%
  dplyr::summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count))

print(observations_by_source_treatment)
```

```{r}
# Observation count by treatment

observations_by_source_treatment <- df_filtered %>%
  group_by(treatment_id) %>%
  dplyr::summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count))

print(observations_by_source_treatment)
```

```{r}
# Observation count for source and treatment combined

observations_by_source_treatment <- df_filtered %>%
  group_by(source, treatment_id) %>%
  dplyr::summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count))

print(observations_by_source_treatment)
```

```{r}
# Observation count for trialID

observations_by_source <- df_filtered %>%
  group_by(trial_id) %>%
  dplyr::summarise(count = n(), .groups = 'drop') %>%
  arrange(desc(count))

print(observations_by_source)
```

```{r}
# Filter trials with only one data point

trials_with_one_data_point <- df_filtered %>%
  group_by(trial_id) %>%
  filter(n() == 1) %>%
  ungroup()

print(trials_with_one_data_point)
```

```{r}
# Count trial_id by location

trial_count_by_location <- aggregate(trial_id ~ location, df_filtered, function(x) length(unique(x)))

# Sort the aggregated data in descending order based on trial count
trial_count_by_location <- trial_count_by_location[order(-trial_count_by_location$trial_id), ]

print(trial_count_by_location)

```

```{r}
df_filtered |> dplyr::group_by(NAME_1) |> dplyr::summarize(n = n()) |>
  dplyr::arrange(desc(n))
```

```{r}
df_filtered |>
ggplot(aes(y = grain_yield_kgpha, fill = NAME_1))+
  geom_boxplot(width = 0.2, outlier.colour = 'red')+
  theme_bw()+
  theme(axis.text.x = element_blank(), legend.position = "right")+
   guides(fill = guide_legend(nrow = 4))
```

```{r}
avg_yld_zone <- df_filtered |> dplyr::group_by(NAME_1, NAME_2) |> dplyr::summarize(mean_yield = mean(grain_yield_kgpha)) |> dplyr::arrange(desc(mean_yield))
rmarkdown::paged_table(avg_yld_zone, options=NULL) 
```

```{r}
df_filtered |> 
ggplot(aes(y = grain_yield_kgpha, fill = NAME_2))+
  geom_boxplot(width = 0.2, outlier.colour = 'red')+
  facet_wrap(~NAME_1)+
  theme_bw()+
  theme(axis.text.x = element_blank(), legend.position = "none")+
   guides(fill = guide_legend(nrow = 4))
```

```{r}
obs_few_year <- df_filtered |> dplyr::group_by(year) |> dplyr::summarise(n = n()) |> dplyr::arrange(n)
rmarkdown::paged_table(obs_few_year, options=NULL) 
```
```{r}
few_year <- df_filtered |> dplyr::filter(year %in% c(1992, 1998, 1995, 1993, 1994, 1997, 2018)) |> 
  dplyr::group_by(year, trial_id) |> dplyr::summarise(n = n()) |> dplyr::arrange(n)
few_year
```

```{r}
# distribution of yield by district.

ui <- fluidPage(
  titlePanel("Ethiopia Data Locations"),
  sidebarLayout(
    sidebarPanel(
      selectInput("sourceInput", "Select Source",
                  choices = c("All", unique(df_filtered$source)),
                  selected = "All", multiple = TRUE),
      selectInput("treatmentInput", "Select Treatment",
                  choices = c("All", unique(df_filtered$treatment_id)),
                  selected = "All", multiple = TRUE)
    ),
    mainPanel(
      leafletOutput("ethiopiaMap") # Use leafletOutput instead of plotlyOutput
    )
  )
)

server <- function(input, output) {
  output$ethiopiaMap <- renderLeaflet({
    filtered_df <- df_filtered %>%
      filter((source %in% input$sourceInput | input$sourceInput == "All") &
             (treatment_id %in% input$treatmentInput | input$treatmentInput == "All"))
    
    # Initialize a Leaflet map
    leaflet(filtered_df) %>%
      addTiles() %>%  # Add default OpenStreetMap map tiles
      setView(lng = 39.49, lat = 9.145, zoom = 6) %>%
      addCircleMarkers(
        lng = ~X, lat = ~Y,
        popup = ~paste("<b>Source:</b>", source, "<br>",
                       "<b>N:P:K:Yield</b> - ", n_kgpha, ":", p_kgpha, ":", k_kgpha, ":", grain_yield_kgpha,
                       "<br><b>Treatment ID:</b>", treatment_id),
        radius = 5,
        color = ~colorNumeric("viridis", grain_yield_kgpha)(grain_yield_kgpha),
        fillOpacity = 0.8,
        stroke = FALSE,
        labelOptions = labelOptions(noHide = TRUE, direction = "auto")
      ) %>%
      addLegend("bottomright", pal = colorNumeric("viridis", filtered_df$grain_yield_kgpha), values = ~grain_yield_kgpha,
                title = "Grain Yield (kg/ha)",
                opacity = 1)
  })
}

shinyApp(ui = ui, server = server)
```

```{r}
df_filtered <- df_filtered |> dplyr::filter(grain_yield_kgpha <= 15000) 
df_filtered |> 
  ggplot(aes(x = source, y = grain_yield_kgpha, fill = source))+
  geom_boxplot()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8), legend.position = 'none')
```

#### 7. Yield Effect

```{r, warning=FALSE}
# Yield effect (from Meklit) - there are different values of the high NPK yield values.

options(dplyr.summarise.inform = FALSE)
unique_tr_id <- unique(df_filtered$trial_id)
yield_diff_mean <- data.frame()
for(i in 1:length(unique_tr_id)){
  unique_tr_yld <- df_filtered |> dplyr::filter(trial_id ==  unique_tr_id[i])
  max_n <- max(unique_tr_yld$n_rate2)
  max_p <- max(unique_tr_yld$p_rate2)
  max_k <- max(unique_tr_yld$k_rate2)
  unique_tr_yld2 <- unique_tr_yld |> dplyr::filter(n_rate2 == max_n &  p_rate2 == max_p & k_rate2 == max_k)
  if(nrow(unique_tr_yld2) == 0){
      unique_tr_yld2 <- unique_tr_yld |> dplyr::filter(n_rate2 == max_n &  p_rate2 == max_p)
  } 
  if(nrow(unique_tr_yld2) == 0){
      unique_tr_yld2 <- unique_tr_yld |> dplyr::filter(n_rate2 == max_n)
  }
  if(nrow(unique_tr_yld2) > 1){
      ref_yld <- median(unique_tr_yld2$grain_yield_kgpha)
  }else{
      ref_yld <- unique_tr_yld2$grain_yield_kgpha
  }
unique_tr_yld <- unique_tr_yld |> dplyr::mutate(yield_diff = ref_yld - grain_yield_kgpha)
yield_diff_mean <- rbind(yield_diff_mean, unique_tr_yld)
}
saveRDS(yield_diff_mean, "yield_diff.rds")
```


```{r}
# Scatter plot of the yield difference

yield_diff_mean <- yield_diff_mean |> dplyr::mutate(ref_trt = ifelse(yield_diff == 0, T, F))
ref_yld_data <- yield_diff_mean |> dplyr::filter(yield_diff == 0) |> dplyr::select(trial_id, yield_diff, treatment_id, grain_yield_kgpha)
other_yld_data <- yield_diff_mean |> dplyr::filter(yield_diff != 0) |> dplyr::select(trial_id, yield_diff, treatment_id, grain_yield_kgpha)
all_diff_data <- ref_yld_data |> dplyr::inner_join(other_yld_data, by = "trial_id")

all_diff_data  |> ggplot(aes(y = grain_yield_kgpha.x, x = grain_yield_kgpha.y))+
  geom_point()+
  ylab("reference yield")+
  xlab("other treatements yield")+
  geom_abline(intercept = 0, slope = 1, color = 'blue')+
  xlim(0, 10000)+
  ylim(0, 10000)+
  theme_bw()
  #facet_wrap(~year)
```


#### 8. Linear mixed effects model

```{r}
#create variables to deal with scale issues:
df_filtered$year <- as.factor(df_filtered$year)
df_filtered$source <- as.factor(df_filtered$source)
df_filtered$location <- as.factor(df_filtered$location)
df_filtered$trial_id <- as.factor(df_filtered$trial_id)
df_filtered$NAME_2 <- as.factor(df_filtered$NAME_2)

df_filtered$N100 <- df_filtered$n_rate2/100
df_filtered$P100 <- df_filtered$p_rate2/100
df_filtered$K100 <- df_filtered$k_rate2/100
fita <- lmer(sqrt(grain_yield_kgpha) ~ n_rate2 + p_rate2 + k_rate2 + year + (1|trial_id), data= df_filtered)

plot(fita)
fitb <- lmer(sqrt(grain_yield_kgpha) ~ n_rate2 + p_rate2 + k_rate2 + year + (1|trial_id) + source, data = df_filtered)
anova(fita, fitb)

fitc <- lmer(sqrt(grain_yield_kgpha) ~ n_rate2 + p_rate2 + k_rate2 + year + NAME_2 + (1|trial_id) + source, data = df_filtered)
anova(fitb, fitc)

fitd <- lmer(sqrt(grain_yield_kgpha) ~ n_rate2 + p_rate2 + k_rate2 + (1|year) + NAME_2 + (1|trial_id) + source, data = df_filtered)
anova(fitc, fitd)

fite <- update(fitc, . ~ . + N100:P100 + N100:K100 + P100:K100 + N100:P100:K100)
anova(fitc, fite)

fitf <- update(fite, . ~ . +(0 + N100|trial_id) +(0 + P100|trial_id) +(0 + K100|trial_id))
anova(fite, fitf)
#r.squaredGLMM(fitf) 
plot(fitf)
summary(fitf)
df_filtered$blup <- predict(fitf, df_filtered)**2
```
