
source("~/shared-data/Scripts/generic/nutrientResponse/extract_fertilizer_gps_points.R")

## latest NP rate data added
extractAdvice(crop = "Wheat", ExtractionRound = 15, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 16, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 17, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 18, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 19, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 20, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 21, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 22, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 23, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 24, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 26, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 27, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 28, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 29, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 30, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 31, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")
extractAdvice(crop = "Wheat", ExtractionRound = 32, pathIn="shared-data/Data/Wheat/result/geoSpatial/NPrate/NUE_selected")

# ## With missed zones prior to the reun with the latest NP rate data
# extractAdvice(crop = "Wheat", ExtractionRound = 1, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 2, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 3, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 4, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 5, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 6, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 7, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 8, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 9, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 10, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 11, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 12, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 13, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
# extractAdvice(crop = "Wheat", ExtractionRound = 14, pathIn="shared-data/Data/Wheat/result/geoSpatial/final_rate_raster_with_missed_zones")
